# Generated by Django 3.1.3 on 2026-02-27 08:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticExchangeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('staff_user_id', models.IntegerField()),
                ('customer_user_id', models.IntegerField()),
                ('customer_access_token', models.TextField()),
                ('customer_refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'diagnostic_exchange_codes',
            },
        ),
    ]
