# Generated by Django 3.1.3 on 2026-02-27 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticExchangeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('customer_access_token', models.TextField()),
                ('customer_refresh_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('customer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_codes_received', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_codes_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'diagnostic_exchange_codes',
            },
        ),
    ]
