# Generated by Django 4.2.26 on 2026-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticexchangecode',
            name='staff_access_token',
            field=models.TextField(default=''),
        ),
    ]
